name: Upload ZIP to Telegram

on:
  workflow_dispatch:
    inputs:
      ZIP_FILE:
        description: 'Path to the ZIP file to upload'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    environment: Telegram
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug Inputs
      run: |
        echo "ZIP_FILE: ${{ github.event.inputs.ZIP_FILE }}"

    - name: Upload ZIP to Telegram
      run: |
        curl -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
             -F document=@"${{ github.event.inputs.ZIP_FILE }}" \
             -F caption=$'#APLKernel\nFor MIUI/HyperOS, add -miui to the ZIP name; for the 4500 variant, add -bat. Example: ALPKernel-miui-bat-dtb.zip.' \
             -F parse_mode="HTML" \
             https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument
