name: Dispatcher Workflow

on:
  workflow_dispatch:
    inputs:
      UPLOAD_TO_RELEASE:
        description: 'Upload to release for all workflows'
        type: boolean
        default: false
      BUILD_TITLE_ALIOTH_KSUNEXT:
        description: 'Build Title for Kernel Build (alioth) - KSUNEXT ONLY'
        required: false
      BUILD_TITLE_ALIOTH_SUSFS:
        description: 'Build Title for Kernel Build (alioth) - SUSFS + KSU NEXT'
        required: false
      BUILD_TITLE_APOLLO_KSUNEXT:
        description: 'Build Title for Kernel Build (apollo) - KSUNEXT ONLY'
        required: false
      BUILD_TITLE_APOLLO_SUSFS:
        description: 'Build Title for Kernel Build (apollo) - SUSFS + KSU NEXT'
        required: false

jobs:
  trigger-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Kernel Build (alioth) - KSUNEXT ONLY
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'alioth.yml',
              ref: 'main',
              inputs: {
                BUILD_TITLE: '${{ github.event.inputs.BUILD_TITLE_ALIOTH_KSUNEXT }}',
                UPLOAD_TO_RELEASE: ${{ github.event.inputs.UPLOAD_TO_RELEASE }},
              },
            });

      - name: Trigger Kernel Build (alioth) - SUSFS + KSU NEXT
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'susfs.yml',
              ref: 'main',
              inputs: {
                BUILD_TITLE: '${{ github.event.inputs.BUILD_TITLE_ALIOTH_SUSFS }}',
                UPLOAD_TO_RELEASE: ${{ github.event.inputs.UPLOAD_TO_RELEASE }},
              },
            });

      - name: Trigger Kernel Build (apollo) - KSUNEXT ONLY
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'apollo.yml',
              ref: 'main',
              inputs: {
                BUILD_TITLE: '${{ github.event.inputs.BUILD_TITLE_APOLLO_KSUNEXT }}',
                UPLOAD_TO_RELEASE: ${{ github.event.inputs.UPLOAD_TO_RELEASE }},
              },
            });

      - name: Trigger Kernel Build (apollo) - SUSFS + KSU NEXT
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'apollo-susfs.yml',
              ref: 'main',
              inputs: {
                BUILD_TITLE: '${{ github.event.inputs.BUILD_TITLE_APOLLO_SUSFS }}',
                UPLOAD_TO_RELEASE: ${{ github.event.inputs.UPLOAD_TO_RELEASE }},
              },
            });
